# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0C0605"

# Main text color
theme[main_fg]="#F7EBCB"

# Title color for boxes
theme[title]="#F7EBCB"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#5F79D0"

# Background color of selected item in processes box
theme[selected_bg]="#3A2216"

# Foreground color of selected item in processes box
theme[selected_fg]="#5F79D0"

# Color of inactive/disabled text
theme[inactive_fg]="#7A6B5E"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#FBF2DA"

# Background color of the percentage meters
theme[meter_bg]="#3A2216"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#FBF2DA"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#D9A066"
theme[mem_box]="#9CB85A"
theme[net_box]="#BC5C4E"
theme[proc_box]="#5F79D0"

# Box divider line and small boxes line color
theme[div_line]="#7A6B5E"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9CB85A"
theme[temp_mid]="#FFC400"
theme[temp_end]="#BC5C4E"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#7FC8B0"
theme[cpu_mid]="#5F79D0"
theme[cpu_end]="#D9A066"

# Mem/Disk free meter
theme[free_start]="#D9A066"
theme[free_mid]="#5F79D0"
theme[free_end]="#7FC8B0"

# Mem/Disk cached meter
theme[cached_start]="#5F79D0"
theme[cached_mid]="#7FC8B0"
theme[cached_end]="#D9A066"

# Mem/Disk available meter
theme[available_start]="#FFC400"
theme[available_mid]="#BC5C4E"
theme[available_end]="#BC5C4E"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#9CB85A"
theme[used_mid]="#7FC8B0"
theme[used_end]="#5F79D0"

# Download graph colors
theme[download_start]="#FFC400"
theme[download_mid]="#BC5C4E"
theme[download_end]="#BC5C4E"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#9CB85A"
theme[upload_mid]="#7FC8B0"
theme[upload_end]="#5F79D0"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#7FC8B0"
theme[process_mid]="#5F79D0"
theme[process_end]="#D9A066"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#0C0605"
theme[gradient_color_1]="#1C100C"
theme[gradient_color_2]="#3A2216"
theme[gradient_color_3]="#7A6B5E"
theme[gradient_color_4]="#A8987A"
theme[gradient_color_5]="#F7EBCB"
theme[gradient_color_6]="#FBF2DA"
theme[gradient_color_7]="#FFF8EA"
