background = #0C0605
foreground = #F7EBCB
cursor-color = #FFF8EA
selection-background = #3A2216
selection-foreground = #FFF8EA

palette = 0=#0C0605
palette = 1=#BC5C4E
palette = 2=#9CB85A
palette = 3=#FFC400
palette = 4=#5F79D0
palette = 5=#D9A066
palette = 6=#7FC8B0
palette = 7=#F7EBCB
palette = 8=#7A6B5E
palette = 9=#EB7D6A
palette = 10=#B8D47A
palette = 11=#FFD86A
palette = 12=#819AFF
palette = 13=#E8BC88
palette = 14=#A4DFCB
palette = 15=#FFF8EA
