foreground #F7EBCB
background #0C0605
selection_foreground #FFF8EA
selection_background #3A2216

cursor #FFF8EA
cursor_text_color #0C0605

active_border_color #5F79D0
active_tab_background #5F79D0

color0 #0C0605
color1 #BC5C4E
color2 #9CB85A
color3 #FFC400
color4 #5F79D0
color5 #D9A066
color6 #7FC8B0
color7 #F7EBCB
color8 #7A6B5E
color9 #EB7D6A
color10 #B8D47A
color11 #FFD86A
color12 #819AFF
color13 #E8BC88
color14 #A4DFCB
color15 #FFF8EA
