background = #0A0A12
foreground = #E9E6F2
cursor-color = #F8F6FF
selection-background = #241C48
selection-foreground = #F8F6FF

palette = 0=#0A0A12
palette = 1=#C0708E
palette = 2=#5CCFA0
palette = 3=#E6C666
palette = 4=#7F92D0
palette = 5=#A5A6DE
palette = 6=#94CBED
palette = 7=#E9E6F2
palette = 8=#6A6A8C
palette = 9=#D890AA
palette = 10=#85E8BE
palette = 11=#F4D987
palette = 12=#9BAEE8
palette = 13=#BABAFF
palette = 14=#B3FEFF
palette = 15=#F8F6FF
