foreground #E9E6F2
background #0A0A12
selection_foreground #F8F6FF
selection_background #241C48

cursor #F8F6FF
cursor_text_color #0A0A12

active_border_color #7F92D0
active_tab_background #7F92D0

color0 #0A0A12
color1 #C0708E
color2 #5CCFA0
color3 #E6C666
color4 #7F92D0
color5 #A5A6DE
color6 #94CBED
color7 #E9E6F2
color8 #6A6A8C
color9 #D890AA
color10 #85E8BE
color11 #F4D987
color12 #9BAEE8
color13 #BABAFF
color14 #B3FEFF
color15 #F8F6FF
