background = #12100F
foreground = #F3E6C8
cursor-color = #FFF6E2
selection-background = #3A2E22
selection-foreground = #FFF6E2

palette = 0=#12100F
palette = 1=#E0604E
palette = 2=#8DB36A
palette = 3=#E4BE81
palette = 4=#7A8FC4
palette = 5=#C8789A
palette = 6=#6FC3D0
palette = 7=#F3E6C8
palette = 8=#7A746C
palette = 9=#EAAB8B
palette = 10=#A9CE86
palette = 11=#FDC95B
palette = 12=#94A6DF
palette = 13=#DE9AB6
palette = 14=#93D6E0
palette = 15=#FFF6E2
