foreground #F3E6C8
background #12100F
selection_foreground #FFF6E2
selection_background #3A2E22

cursor #FFF6E2
cursor_text_color #12100F

active_border_color #7A8FC4
active_tab_background #7A8FC4

color0 #12100F
color1 #E0604E
color2 #8DB36A
color3 #E4BE81
color4 #7A8FC4
color5 #C8789A
color6 #6FC3D0
color7 #F3E6C8
color8 #7A746C
color9 #EAAB8B
color10 #A9CE86
color11 #FDC95B
color12 #94A6DF
color13 #DE9AB6
color14 #93D6E0
color15 #FFF6E2
