background = #070A12
foreground = #F4EBDD
cursor-color = #FFF8EE
selection-background = #1C2236
selection-foreground = #FFF8EE

palette = 0=#070A12
palette = 1=#FF4D5E
palette = 2=#3FD6A6
palette = 3=#F2C14E
palette = 4=#8A8ACD
palette = 5=#B09CDF
palette = 6=#9BDCFF
palette = 7=#F4EBDD
palette = 8=#6B6A78
palette = 9=#FF7A87
palette = 10=#6AE8C0
palette = 11=#FFD36A
palette = 12=#A9AAF0
palette = 13=#C8AEFF
palette = 14=#AEF8FF
palette = 15=#FFF8EE
