$color = rgba(0, 0, 14, 1.0)
$inner_color = rgba(16, 20, 38, 0.8)
$outer_color = rgba(56, 71, 255, 1.0)
$font_color = rgba(230, 230, 230, 1.0)
$placeholder_color = rgba(133, 138, 166, 0.7)
$check_color = rgba(214, 130, 90, 1.0)
