foreground #F4EBDD
background #070A12
selection_foreground #FFF8EE
selection_background #1C2236

cursor #FFF8EE
cursor_text_color #070A12

active_border_color #8A8ACD
active_tab_background #8A8ACD

color0 #070A12
color1 #FF4D5E
color2 #3FD6A6
color3 #F2C14E
color4 #8A8ACD
color5 #B09CDF
color6 #9BDCFF
color7 #F4EBDD
color8 #6B6A78
color9 #FF7A87
color10 #6AE8C0
color11 #FFD36A
color12 #A9AAF0
color13 #C8AEFF
color14 #AEF8FF
color15 #FFF8EE
